name: Build and release

on:
  push:
    tags:
      - 'V*'
    paths-ignore:
      - 'README.md'
      - 'CHANGE.md'
      - 'doc/*'
      - '.github/*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_AUTH_TOKEN }}
          repository: ircbloqcc/ircbloq-releases
          path: ircbloq-releases

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Create tag in public repository
        run: |
          cd ${{github.workspace}}/ircbloq-releases
          git tag ${{ steps.get_tag.outputs.tag }}
          git push --tags --porcelain
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          owner: ircbloqcc
          repo: ircbloq-releases
          tag: ${{ steps.get_tag.outputs.tag }}
          name: Release ${{ steps.get_tag.outputs.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
          token:  ${{ secrets.REPO_AUTH_TOKEN }}

  build-windows:
    needs: create-release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: github Token
        run: git config --global url."https://${{ secrets.REPO_AUTH_TOKEN }}@github.com/".insteadOf ssh://git@github.com/

      - name: Npm Install
        run: |
          npm ci

      - name: Build and Publish
        env:
          GA_ID: ${{ secrets.GA_ID }}
          GH_TOKEN: ${{ secrets.REPO_AUTH_TOKEN }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run publish

  build-mac:
    needs: create-release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: github Token
        run: git config --global url."https://${{ secrets.REPO_AUTH_TOKEN }}@github.com/".insteadOf ssh://git@github.com/

      - name: Npm Install
        run: npm ci

      - name: Build and Publish
        env:
          GA_ID: ${{ secrets.GA_ID }}
          GH_TOKEN: ${{ secrets.REPO_AUTH_TOKEN }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run publish
