name: Build and release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - 'CHANGE.md'
      - 'doc/*'
      - '.github/*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: node version
        run : node --version
      
      - name: npm version
        run : npm --version
        
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/

      - name: Npm Install
        run: npm install
